name: llm-math
channels:
  - defaults
  - pip
dependencies:
  - pip=23.2.1
  - python=3.10.12
  - pip:
    - torch
    - transformers==4.40.0
    - accelerate
    - python-dotenv
    - torchtune
    - tqdm
    - torch==2.1.2
    - pathlib==1.0.1
    - datasets
    - huggingface_hub[torch, cli]
    - python-dotenv
    - notebook
    - open_flamingo
    - transformers
    # - -r requirements.txt